Root:
  - changed-files:
      - any-glob-to-any-file: "*"

WorkFlows:
  - changed-files:
  - any-glob-to-any-file: .github/**

Documentation:
  - changed-files:
      - any-glob-to-any-file: docs/vitepress/**

Scripts:
  - changed-files:
      - any-glob-to-any-file: scripts/**

Source:
  - changed-files:
      - any-glob-to-any-file: "packages/**/src/**/*"

Tests:
  - changed-files:
      - any-glob-to-any-file: "packages/**/__tests__/**/*"

AllPackage:
  - changed-files:
      - any-glob-to-any-file: "packages/all/**/*"

ArrPackage:
  - changed-files:
      - any-glob-to-any-file: "packages/arr/**/*"

CollectionPackage:
  - changed-files:
      - any-glob-to-any-file: "packages/collection/**/*"

DataPackage:
  - changed-files:
      - any-glob-to-any-file: "packages/data/**/*"

NumberPackage:
  - changed-files:
      - any-glob-to-any-file: "packages/num/**/*"

ObjectPackage:
  - changed-files:
      - any-glob-to-any-file: "packages/obj/**/*"

PathPackage:
  - changed-files:
      - any-glob-to-any-file: "packages/path/**/*"

StringPackage:
  - changed-files:
      - any-glob-to-any-file: "packages/str/**/*"

TypesPackage:
  - changed-files:
      - any-glob-to-any-file: "packages/types/**/*"

UtilsPackage:
  - changed-files:
      - any-glob-to-any-file: "packages/utils/**/*"

# Add 'feature' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
Feature:
  - head-branch: ["^feature", "feature"]

Release:
  - base-branch: "master"
