packages:
  - packages/*

configDependencies:
  "@pnpm/plugin-types-fixer": 0.1.0+sha512-bLww63gRHi7siYTqFJb5qNdcXadU0jv20Et6z5AryMZ7FlLolbEJOrXLpg8+amQZNHHNW1dfFUBGVw/9ezQbFg==

linkWorkspacePackages: true

catalogs:
  num:
    to-words: ^4.7.0
  str:
    any-ascii: ^0.3.3
    markdown-it: ^14.1.0
    markdown-it-anchor: ^9.2.0
    markdown-it-task-lists: ^2.1.1
    pluralize: ^8.0.0
    transliteration: ^2.3.5
    ulid: ^2.4.0
    uuid: ^11.1.0
  types:
    "@types/markdown-it": ^14.1.2
    "@types/pluralize": ^0.0.33
